import pygame

#Why is this so scuffed? No idea. If you can help us improve it please let me know by opening an issue on the github or whatever. I am going insane

walking_sprite0 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite1 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite2 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite3 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite4 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite5 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite6 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")
walking_sprite7 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(1).png")

walking_sprite8 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite9 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite10 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite11 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite12 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite13 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite14 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")
walking_sprite15 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(2).png")

walking_sprite16 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite17 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite18 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite19 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite20 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite21 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite22 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")
walking_sprite23 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(3).png")

walking_sprite24 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite25 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite26 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite27 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite28 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite29 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite30 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")
walking_sprite31 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(4).png")

walking_sprite32 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite33 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite34 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite35 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite36 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite37 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite38 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")
walking_sprite39 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(5).png")

walking_sprite40 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite41 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite42 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite43 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite44 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite45 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite46 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")
walking_sprite47 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(6).png")

walking_sprite48 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite49 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite50 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite51 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite52 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite53 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite54 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")
walking_sprite55 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Running/1running(7).png")

walking_sprite = [walking_sprite0, walking_sprite1, walking_sprite2, walking_sprite3, walking_sprite4, walking_sprite5,  walking_sprite7, walking_sprite8, walking_sprite9, walking_sprite10, walking_sprite11, walking_sprite12, walking_sprite14, walking_sprite15, walking_sprite16, walking_sprite17, walking_sprite18,  walking_sprite20, walking_sprite21, walking_sprite22, walking_sprite23, walking_sprite24, walking_sprite25, walking_sprite27, walking_sprite28, walking_sprite29, walking_sprite30, walking_sprite31, walking_sprite32, walking_sprite33, walking_sprite34, walking_sprite36, walking_sprite37, walking_sprite38, walking_sprite39, walking_sprite40, walking_sprite41, walking_sprite43, walking_sprite44, walking_sprite45, walking_sprite46, walking_sprite47, walking_sprite48, walking_sprite50, walking_sprite51, walking_sprite52, walking_sprite53, walking_sprite54, walking_sprite55]


idle_sprite0 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite1 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite2 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite3 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite4 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite5 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite6 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite7 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite8 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")
idle_sprite9 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(1).png")

idle_sprite10 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite11 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite12 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite13 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite14 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite15 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite16 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite17 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite18 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")
idle_sprite19 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(2).png")

idle_sprite20 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite21 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite22 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite23 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite24 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite25 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite26 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite27 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite28 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")
idle_sprite29 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(3).png")

idle_sprite30 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite31 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite32 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite33 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite34 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite35 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite36 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite37 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite38 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")
idle_sprite39 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(4).png")

idle_sprite40 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite41 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite42 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite43 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite44 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite45 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite46 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite47 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite48 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")
idle_sprite49 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(5).png")

idle_sprite50 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite51 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite52 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite53 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite54 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite55 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite56 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite57 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite58 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")
idle_sprite59 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(6).png")

idle_sprite60 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite61 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite62 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite63 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite64 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite65 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite66 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite67 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite68 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")
idle_sprite69 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Idle/1idle(7).png")

idle_sprite = [idle_sprite0, idle_sprite1, idle_sprite2, idle_sprite3, idle_sprite4, idle_sprite5, idle_sprite6, idle_sprite7, idle_sprite8, idle_sprite9, idle_sprite10, idle_sprite11, idle_sprite12, idle_sprite13, idle_sprite14, idle_sprite15, idle_sprite16, idle_sprite17, idle_sprite18, idle_sprite19, idle_sprite20, idle_sprite21, idle_sprite22, idle_sprite23, idle_sprite24, idle_sprite25, idle_sprite26, idle_sprite27, idle_sprite28, idle_sprite29, idle_sprite30, idle_sprite31, idle_sprite32, idle_sprite33, idle_sprite34, idle_sprite35, idle_sprite36, idle_sprite37, idle_sprite38, idle_sprite39, idle_sprite40, idle_sprite41, idle_sprite42, idle_sprite43, idle_sprite44, idle_sprite45, idle_sprite46, idle_sprite47, idle_sprite48, idle_sprite49, idle_sprite50, idle_sprite51, idle_sprite52, idle_sprite53, idle_sprite54, idle_sprite55, idle_sprite56, idle_sprite57, idle_sprite58, idle_sprite59, idle_sprite60, idle_sprite61, idle_sprite62, idle_sprite63, idle_sprite64, idle_sprite65, idle_sprite66, idle_sprite67, idle_sprite68, idle_sprite69]


jump_sprite0 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite1 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite2 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite3 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite4 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite5 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite6 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")
jump_sprite7 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(1).png")

jump_sprite8 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite9 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite10 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite11 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite12 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite13 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite14 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")
jump_sprite15 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(2).png")

jump_sprite16 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite17 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite18 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite19 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite20 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite21 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite22 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")
jump_sprite23 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(3).png")

jump_sprite24 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite25 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite26 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite27 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite28 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite29 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite30 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")
jump_sprite31 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(4).png")

jump_sprite32 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite33 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite34 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite35 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite36 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite37 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite38 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")
jump_sprite39 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(5).png")

jump_sprite40 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite41 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite42 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite43 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite44 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite45 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite46 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")
jump_sprite47 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(6).png")

jump_sprite48 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite49 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite50 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite51 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite52 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite53 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite54 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")
jump_sprite55 = pygame.image.load("src\main/assets/textures\entities\characters\character_1/animations/1Jump/1Jump(7).png")

jump_sprite = [jump_sprite0, jump_sprite1, jump_sprite2, jump_sprite3, jump_sprite4, jump_sprite5, jump_sprite6, jump_sprite7, jump_sprite8, jump_sprite9, jump_sprite10, jump_sprite11, jump_sprite12, jump_sprite13, jump_sprite14, jump_sprite15, jump_sprite16, jump_sprite17, jump_sprite18, jump_sprite19, jump_sprite20, jump_sprite21, jump_sprite22, jump_sprite23, jump_sprite24, jump_sprite25, jump_sprite26, jump_sprite27, jump_sprite28, jump_sprite29, jump_sprite30, jump_sprite31, jump_sprite32, jump_sprite33, jump_sprite34, jump_sprite35, jump_sprite36, jump_sprite37, jump_sprite38, jump_sprite39, jump_sprite40, jump_sprite41, jump_sprite42, jump_sprite43, jump_sprite44, jump_sprite45, jump_sprite46, jump_sprite47, jump_sprite48, jump_sprite49, jump_sprite50, jump_sprite51, jump_sprite52, jump_sprite53, jump_sprite54, jump_sprite55]


optionsButton0 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(1).png")
optionsButton1 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(1).png")
optionsButton2 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(1).png")
optionsButton3 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(1).png")

optionsButton4 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(2).png")
optionsButton5 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(2).png")
optionsButton6 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(2).png")
optionsButton7 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(2).png")

optionsButton8 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(3).png")
optionsButton9 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(3).png")
optionsButton10 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(3).png")
optionsButton11 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(3).png")

optionsButton12 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(4).png")
optionsButton13 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(4).png")
optionsButton14 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(4).png")
optionsButton15 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(4).png")

optionsButton16 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(5).png")
optionsButton17 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(5).png")
optionsButton18 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(5).png")
optionsButton19 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(5).png")

optionsButton20 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(6).png")
optionsButton21 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(6).png")
optionsButton22 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(6).png")
optionsButton23 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(6).png")

optionsButton24 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(7).png")
optionsButton25 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(7).png")
optionsButton26 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel\OptionButtonSel(7).png")
optionsButton27 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel/OptionButtonSel(7).png")

optionsButton28 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel/OptionButtonSel(8).png")
optionsButton29 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel/OptionButtonSel(8).png")
optionsButton30 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel/OptionButtonSel(8).png")
optionsButton31 = pygame.image.load("src\main/assets/textures\elements\gui\OptionsButtonSel/OptionButtonSel(8).png")

optionsButton = [optionsButton0, optionsButton1, optionsButton2, optionsButton3, optionsButton4, optionsButton5, optionsButton6, optionsButton7, optionsButton8, optionsButton9, optionsButton10, optionsButton11, optionsButton12, optionsButton13, optionsButton14, optionsButton15, optionsButton16, optionsButton17, optionsButton18, optionsButton19, optionsButton20, optionsButton21, optionsButton22, optionsButton23, optionsButton24, optionsButton25, optionsButton26, optionsButton27, optionsButton28, optionsButton29, optionsButton30, optionsButton31]


startButton0 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(1).png")
startButton1 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(1).png")
startButton2 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(1).png")
startButton3 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(1).png")

startButton4 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(2).png")
startButton5 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(2).png")
startButton6 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(2).png")
startButton7 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(2).png")

startButton8 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(3).png")
startButton9 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(3).png")
startButton10 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(3).png")
startButton11 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(3).png")

startButton12 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(4).png")
startButton13 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(4).png")
startButton14 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(4).png")
startButton15 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(4).png")

startButton16 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(5).png")
startButton17 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(5).png")
startButton18 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(5).png")
startButton19 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(5).png")

startButton20 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(6).png")
startButton21 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(6).png")
startButton22 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(6).png")
startButton23 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(6).png")

startButton24 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(7).png")
startButton25 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(7).png")
startButton26 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel\StartButtonSel(7).png")
startButton27 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel/StartButtonSel(7).png")

startButton28 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel/StartButtonSel(8).png")
startButton29 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel/StartButtonSel(8).png")
startButton30 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel/StartButtonSel(8).png")
startButton31 = pygame.image.load("src\main/assets/textures\elements\gui\StartButtonSel/StartButtonSel(8).png")

startButton = [startButton0, startButton1, startButton2, startButton3, startButton4, startButton5, startButton6, startButton7, startButton8, startButton9, startButton10, startButton11, startButton12, startButton13, startButton14, startButton15, startButton16, startButton17, startButton18, startButton19, startButton20, startButton21, startButton22, startButton23, startButton24, startButton25, startButton26, startButton27, startButton28, startButton29, startButton30, startButton31]

quitButton0 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(1).png")
quitButton1 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(1).png")
quitButton2 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(1).png")
quitButton3 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(1).png")

quitButton4 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(2).png")
quitButton5 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(2).png")
quitButton6 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(2).png")
quitButton7 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(2).png")

quitButton8 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(3).png")
quitButton9 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(3).png")
quitButton10 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(3).png")
quitButton11 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(3).png")

quitButton12 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(4).png")
quitButton13 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(4).png")
quitButton14 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(4).png")
quitButton15 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(4).png")

quitButton16 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(5).png")
quitButton17 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(5).png")
quitButton18 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(5).png")
quitButton19 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(5).png")

quitButton20 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(6).png")
quitButton21 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(6).png")
quitButton22 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(6).png")
quitButton23 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(6).png")

quitButton24 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(7).png")
quitButton25 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(7).png")
quitButton26 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel\QuitButtonSel(7).png")
quitButton27 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel/QuitButtonSel(7).png")

quitButton28 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel/QuitButtonSel(8).png")
quitButton29 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel/QuitButtonSel(8).png")
quitButton30 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel/QuitButtonSel(8).png")
quitButton31 = pygame.image.load("src\main/assets/textures\elements\gui\QuitButtonSel/QuitButtonSel(8).png")

quitButton = [quitButton0, quitButton1, quitButton2, quitButton3, quitButton4, quitButton5, quitButton6, quitButton7, quitButton8, quitButton9, quitButton10, quitButton11, quitButton12, quitButton13, quitButton14, quitButton15, quitButton16, quitButton17, quitButton18, quitButton19, quitButton20, quitButton21, quitButton22, quitButton23, quitButton24, quitButton25, quitButton26, quitButton27, quitButton28, quitButton29, quitButton30, quitButton31]